# las variables de entorno de la base de datos las asignaremos aqui pero en un entorno de produccion deberian ir
# en docker secrets
version: '3.9'

services:
  java_app:
    container_name: java_app
    image: todo-java-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATASOURCE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

# - no asignamos a ninguna red porque por defecto ira a la misma red
# - no asignamos volúmenes de momento, pero podriamos almacenar la base de datos si quisieramos

